on :
  push :
    branches : [ "master" ]
  pull_request:
    branches : [ "master" ]

permissions :
  contents: read

jobs:
  build:

    runs-on: debian-latest

    steps:
    - uses: action/checkout@v4

    - name : Validate composer.json and composer.lock 
      run : composer validate --strict
